import { Alert, Box, Button, Card, CardContent, CircularProgress, Stack, Typography } from "@mui/material";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

import { fetchOrGenerateLlmExplanation } from "../api/analysis";
import { quietSurface } from "../theme";

export interface LlmExplanationPanelProps {
  analysisId: string;
  token: string;
  /** From `AIAnalysis.llm_explanation_available` — a cached explanation
   * already exists server-side, so the first click can show it instead of
   * calling Ollama again. */
  explanationAvailable: boolean;
  /** From `AIAnalysis.llm_explanation_error` — the honest reason the last
   * generation attempt failed, shown up front without a click if present. */
  explanationError: string | null;
}

/**
 * EPIC-18: on-demand natural-language explanation of the analysis,
 * generated by a local LLM (Ollama + Qwen2.5, see ADR-9) from the same
 * structured fields (predicted_class/probabilities/biomarker_consistency)
 * already shown elsewhere on this card — never from the Grad-CAM array,
 * which isn't spatially meaningful (see GradcamPanel's own note). Same
 * quiet-tier, lazy-fetch-on-click pattern as GradcamPanel: nothing is
 * generated until the clinician explicitly asks for it.
 */
export function LlmExplanationPanel({
  analysisId,
  token,
  explanationAvailable,
  explanationError,
}: LlmExplanationPanelProps) {
  const { t, i18n } = useTranslation();
  const [expanded, setExpanded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(explanationError);
  // The language the *currently shown* explanation was actually generated
  // in — not necessarily i18n.language yet, since generation is async.
  // Drives the effect below: when the UI language changes, the backend's
  // own per-language cache decides whether that's a real regeneration or a
  // cache hit (see POST .../explanation), this just makes sure the request
  // fires.
  const shownLanguageRef = useRef<string | null>(null);

  function generate(force: boolean) {
    setLoading(true);
    setError(null);
    const requestedLanguage = i18n.language;
    fetchOrGenerateLlmExplanation(analysisId, token, force, requestedLanguage)
      .then((result) => {
        setExplanation(result.explanation);
        setError(result.error);
        shownLanguageRef.current = requestedLanguage;
      })
      .catch((err) => {
        setError(err instanceof Error ? err.message : "Could not generate an explanation");
      })
      .finally(() => setLoading(false));
  }

  function handleToggle() {
    const next = !expanded;
    setExpanded(next);
    if (next && explanation === null && !loading) {
      generate(false);
    }
  }

  // Follows the site-wide language toggle: if the panel is open and already
  // showing something in a different language than what's now selected,
  // re-fetch (the backend serves its own cache when that language was
  // already generated before, or generates fresh otherwise — see
  // POST .../explanation's per-language cache).
  useEffect(() => {
    if (expanded && !loading && shownLanguageRef.current !== null && shownLanguageRef.current !== i18n.language) {
      generate(false);
    }
  }, [i18n.language]);

  return (
    <Card sx={{ ...quietSurface(), mt: 2 }}>
      <CardContent>
        <Stack direction="row" justifyContent="space-between" alignItems="center" flexWrap="wrap" useFlexGap spacing={1}>
          <Typography variant="subtitle1">{t("llmExplanation.title")}</Typography>
          <Button size="small" variant="outlined" onClick={handleToggle} aria-expanded={expanded}>
            {expanded
              ? t("llmExplanation.hide")
              : explanationAvailable
                ? t("llmExplanation.view")
                : t("llmExplanation.generate")}
          </Button>
        </Stack>

        {expanded && (
          <Box sx={{ mt: 2 }}>
            <Alert severity="warning" sx={{ mb: 2 }}>
              {t("llmExplanation.disclaimer")}
            </Alert>

            {loading && (
              <Stack direction="row" spacing={1} alignItems="center">
                <CircularProgress size={18} />
                <Typography variant="body2" color="text.secondary">
                  {t("llmExplanation.generating")}
                </Typography>
              </Stack>
            )}

            {!loading && error && <Alert severity="error">{error}</Alert>}

            {!loading && explanation && (
              <Stack spacing={1.5}>
                <Typography variant="body2" sx={{ whiteSpace: "pre-line" }}>
                  {explanation}
                </Typography>
                <Button size="small" onClick={() => generate(true)} sx={{ alignSelf: "flex-start" }}>
                  {t("llmExplanation.regenerate")}
                </Button>
              </Stack>
            )}
          </Box>
        )}
      </CardContent>
    </Card>
  );
}
