import { Alert, Box, Button, Card, CardContent, CircularProgress, Stack, Typography } from "@mui/material";
import { useState } from "react";

import { fetchOrGenerateLlmExplanation } from "../api/analysis";
import { quietSurface } from "../theme";

export interface LlmExplanationPanelProps {
  analysisId: string;
  token: string;
  /** From `AIAnalysis.llm_explanation_available` — a cached explanation
   * already exists server-side, so the first click can show it instead of
   * calling Ollama again. */
  explanationAvailable: boolean;
  /** From `AIAnalysis.llm_explanation_error` — the honest reason the last
   * generation attempt failed, shown up front without a click if present. */
  explanationError: string | null;
}

/**
 * EPIC-18: on-demand natural-language explanation of the analysis,
 * generated by a local LLM (Ollama + Qwen2.5, see ADR-9) from the same
 * structured fields (predicted_class/probabilities/biomarker_consistency)
 * already shown elsewhere on this card — never from the Grad-CAM array,
 * which isn't spatially meaningful (see GradcamPanel's own note). Same
 * quiet-tier, lazy-fetch-on-click pattern as GradcamPanel: nothing is
 * generated until the clinician explicitly asks for it.
 */
export function LlmExplanationPanel({
  analysisId,
  token,
  explanationAvailable,
  explanationError,
}: LlmExplanationPanelProps) {
  const [expanded, setExpanded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(explanationError);

  function generate(force: boolean) {
    setLoading(true);
    setError(null);
    fetchOrGenerateLlmExplanation(analysisId, token, force)
      .then((result) => {
        setExplanation(result.explanation);
        setError(result.error);
      })
      .catch((err) => {
        setError(err instanceof Error ? err.message : "Could not generate an explanation");
      })
      .finally(() => setLoading(false));
  }

  function handleToggle() {
    const next = !expanded;
    setExpanded(next);
    if (next && explanation === null && !loading) {
      generate(false);
    }
  }

  return (
    <Card sx={{ ...quietSurface(), mt: 2 }}>
      <CardContent>
        <Stack direction="row" justifyContent="space-between" alignItems="center" flexWrap="wrap" useFlexGap spacing={1}>
          <Typography variant="subtitle1">AI-suggested explanation</Typography>
          <Button size="small" variant="outlined" onClick={handleToggle} aria-expanded={expanded}>
            {expanded ? "Hide explanation" : explanationAvailable ? "View explanation" : "Generate explanation"}
          </Button>
        </Stack>

        {expanded && (
          <Box sx={{ mt: 2 }}>
            <Alert severity="warning" sx={{ mb: 2 }}>
              Sugerencia de apoyo a la decisión, redactada por un modelo de lenguaje (Qwen2.5, local) a
              partir de los valores ya calculados por el sistema — no es un diagnóstico. Verifica si
              tiene sentido clínico antes de tenerla en cuenta.
            </Alert>

            {loading && (
              <Stack direction="row" spacing={1} alignItems="center">
                <CircularProgress size={18} />
                <Typography variant="body2" color="text.secondary">
                  Generando explicación…
                </Typography>
              </Stack>
            )}

            {!loading && error && <Alert severity="error">{error}</Alert>}

            {!loading && explanation && (
              <Stack spacing={1.5}>
                <Typography variant="body2" sx={{ whiteSpace: "pre-line" }}>
                  {explanation}
                </Typography>
                <Button size="small" onClick={() => generate(true)} sx={{ alignSelf: "flex-start" }}>
                  Regenerate
                </Button>
              </Stack>
            )}
          </Box>
        )}
      </CardContent>
    </Card>
  );
}
