"""EPIC-18: natural-language explanation of an AIAnalysis, generated by a
local LLM (Ollama + Qwen2.5, see ADR-9 and docs/llm-explanation.md) rather
than a template — the whole point is a clinician-readable narrative, not a
restatement of numbers they can already see in the UI.

The prompt is built ONLY from fields already computed and stored on the
AIAnalysis (predicted_class, probabilities, biomarker_consistency) — never
from the Grad-CAM attribution array, which lives in the model's own working
space and isn't spatially aligned with the real anatomy (see
AIAnalysis.gradcam_storage_key's docstring and EPIC-14's "Contrato técnico"
for why that array is never treated as if it were). Letting an LLM narrate
"what the model is looking at" from that array would mean fabricating a
spatial claim the data doesn't support — exactly what this project's
clinical-limitations.md already commits to never doing.

Ollama runs natively on the host, reached the same way the DL training
runner is (see app.services.dl_inference_client / ADR-8) — this call can
fail (Ollama not running, model not pulled yet, a bad response) and that
failure is never hidden: the caller always gets a clear
`LlmExplanationError`, never a silently fabricated string.
"""
import httpx

from app.core.config import get_settings
from app.models.ai_analysis import AIAnalysis

# Generous — a 7B model's first call after `ollama serve` starts has to load
# the weights into memory (can take tens of seconds), and this call is
# already off any hot path (explicitly triggered by a clinician clicking
# "Generate explanation", not on every page load).
_GENERATION_TIMEOUT_S = 90.0

_SYSTEM_PROMPT = (
    "Eres un asistente que redacta, en espanol, un resumen breve y claro para un "
    "profesional clinico a partir de resultados YA CALCULADOS por un sistema de IA "
    "(clasificacion de imagen cardiaca y una senal de consistencia de biomarcadores). "
    "No inventes hallazgos ni valores que no se te den. No emitas un diagnostico ni "
    "una recomendacion de tratamiento. Presenta el texto explicitamente como una "
    "sugerencia de apoyo a la decision que el profesional debe verificar por su "
    "propio criterio clinico, nunca como una conclusion cerrada. Maximo 4 frases."
)


class LlmExplanationError(RuntimeError):
    """Raised for anything that stops a real explanation from being
    generated — unreachable Ollama, the model not pulled yet, a bad/empty
    response. Always caught by the API layer and turned into an honest
    `llm_explanation_error` on the AIAnalysis, never a crash and never a
    fabricated fallback string."""


def _format_biomarker_consistency(biomarker_consistency: dict | None) -> str:
    if not biomarker_consistency:
        return "No hay señal de consistencia de biomarcadores disponible para este análisis."
    lines = []
    for feature in biomarker_consistency.get("per_feature", []):
        consistent = "consistente" if feature.get("consistent") else "fuera de lo esperado"
        lines.append(
            f"- {feature['feature']}: valor derivado {feature['derived_value']:.2f} "
            f"(esperado para esta clase: {feature['expected_value_for_predicted_class']:.2f}, "
            f"desviación escalada {feature['scaled_deviation']:.2f} — {consistent})"
        )
    return "\n".join(lines) if lines else "Sin features individuales reportadas."


def build_prompt(analysis: AIAnalysis) -> str:
    probabilities = analysis.probabilities or {}
    prob_lines = "\n".join(f"- {cls}: {p:.1%}" for cls, p in sorted(probabilities.items(), key=lambda kv: -kv[1]))
    return (
        f"Clase predicha por el modelo: {analysis.predicted_class}\n"
        f"Probabilidades por clase:\n{prob_lines}\n\n"
        f"Consistencia de biomarcadores derivados frente a lo esperado para la clase predicha:\n"
        f"{_format_biomarker_consistency(analysis.biomarker_consistency)}\n\n"
        "Redacta el resumen para el profesional ahora, siguiendo las instrucciones del sistema."
    )


def generate_explanation(analysis: AIAnalysis) -> str:
    settings = get_settings()
    prompt = build_prompt(analysis)
    try:
        response = httpx.post(
            f"{settings.ollama_url}/api/generate",
            json={
                "model": settings.ollama_model,
                "system": _SYSTEM_PROMPT,
                "prompt": prompt,
                "stream": False,
            },
            timeout=_GENERATION_TIMEOUT_S,
        )
    except httpx.HTTPError as exc:
        raise LlmExplanationError(
            f"could not reach Ollama at {settings.ollama_url} "
            f"(is it running? see docs/llm-explanation.md): {exc}"
        ) from exc
    if response.status_code != 200:
        raise LlmExplanationError(f"Ollama returned {response.status_code}: {response.text}")
    body = response.json()
    text = (body.get("response") or "").strip()
    if not text:
        raise LlmExplanationError("Ollama returned an empty response")
    return text
