"""EPIC-18: natural-language explanation of an AIAnalysis, generated by a
local LLM (Ollama + Qwen2.5, see ADR-9 and docs/llm-explanation.md) rather
than a template — the whole point is a clinician-readable narrative, not a
restatement of numbers they can already see in the UI.

The prompt is built ONLY from fields already computed and stored on the
AIAnalysis (predicted_class, probabilities, biomarker_consistency) — never
from the Grad-CAM attribution array, which lives in the model's own working
space and isn't spatially aligned with the real anatomy (see
AIAnalysis.gradcam_storage_key's docstring and EPIC-14's "Contrato técnico"
for why that array is never treated as if it were). Letting an LLM narrate
"what the model is looking at" from that array would mean fabricating a
spatial claim the data doesn't support — exactly what this project's
clinical-limitations.md already commits to never doing.

Ollama runs natively on the host, reached the same way the DL training
runner is (see app.services.dl_inference_client / ADR-8) — this call can
fail (Ollama not running, model not pulled yet, a bad response) and that
failure is never hidden: the caller always gets a clear
`LlmExplanationError`, never a silently fabricated string.
"""
import httpx

from app.core.config import get_settings
from app.models.ai_analysis import AIAnalysis

# Generous — a 7B model's first call after `ollama serve` starts has to load
# the weights into memory (can take tens of seconds), and this call is
# already off any hot path (explicitly triggered by a clinician clicking
# "Generate explanation", not on every page load).
_GENERATION_TIMEOUT_S = 90.0

# Matches SUPPORTED_LANGUAGES in frontend/src/i18n/index.ts — the UI's own
# language toggle (EPIC-18 follow-up) drives which of these the endpoint
# asks Ollama for, so the suggestion reads in whichever language the
# clinician is already using, not always Spanish/English regardless of it.
DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("en", "es")

_SYSTEM_PROMPTS = {
    "es": (
        "Eres un asistente que redacta, en español, un resumen breve y claro para un "
        "profesional clínico a partir de resultados YA CALCULADOS por un sistema de IA "
        "(clasificación de imagen cardíaca y una señal de consistencia de biomarcadores). "
        "No inventes hallazgos ni valores que no se te den. No emitas un diagnóstico ni "
        "una recomendación de tratamiento. Presenta el texto explícitamente como una "
        "sugerencia de apoyo a la decisión que el profesional debe verificar por su "
        "propio criterio clínico, nunca como una conclusión cerrada. Máximo 4 frases."
    ),
    "en": (
        "You are an assistant who writes, in English, a short and clear summary for a "
        "clinical professional from results a system ALREADY COMPUTED (cardiac image "
        "classification and a biomarker-consistency signal). Never invent findings or "
        "values you weren't given. Never issue a diagnosis or a treatment recommendation. "
        "Present the text explicitly as a decision-support suggestion the professional "
        "must verify against their own clinical judgment, never as a closed conclusion. "
        "Maximum 4 sentences."
    ),
}

_PROMPT_LABELS = {
    "es": {
        "predicted_class": "Clase predicha por el modelo",
        "probabilities": "Probabilidades por clase",
        "consistency": "Consistencia de biomarcadores derivados frente a lo esperado para la clase predicha",
        "no_consistency": "No hay señal de consistencia de biomarcadores disponible para este análisis.",
        "no_features": "Sin features individuales reportadas.",
        "consistent": "consistente",
        "deviates": "fuera de lo esperado",
        "expected": "esperado para esta clase",
        "scaled_deviation": "desviación escalada",
        "closing": "Redacta el resumen para el profesional ahora, siguiendo las instrucciones del sistema.",
    },
    "en": {
        "predicted_class": "Model's predicted class",
        "probabilities": "Per-class probabilities",
        "consistency": "Derived biomarker consistency against what's expected for the predicted class",
        "no_consistency": "No biomarker consistency signal is available for this analysis.",
        "no_features": "No individual features reported.",
        "consistent": "consistent",
        "deviates": "outside the expected range",
        "expected": "expected for this class",
        "scaled_deviation": "scaled deviation",
        "closing": "Write the summary for the professional now, following the system instructions.",
    },
}


class LlmExplanationError(RuntimeError):
    """Raised for anything that stops a real explanation from being
    generated — unreachable Ollama, the model not pulled yet, a bad/empty
    response. Always caught by the API layer and turned into an honest
    `llm_explanation_error` on the AIAnalysis, never a crash and never a
    fabricated fallback string."""


def _normalize_language(language: str) -> str:
    return language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def _format_biomarker_consistency(biomarker_consistency: dict | None, labels: dict[str, str]) -> str:
    if not biomarker_consistency:
        return labels["no_consistency"]
    lines = []
    for feature in biomarker_consistency.get("per_feature", []):
        consistent = labels["consistent"] if feature.get("consistent") else labels["deviates"]
        lines.append(
            f"- {feature['feature']}: {feature['derived_value']:.2f} "
            f"({labels['expected']}: {feature['expected_value_for_predicted_class']:.2f}, "
            f"{labels['scaled_deviation']} {feature['scaled_deviation']:.2f} — {consistent})"
        )
    return "\n".join(lines) if lines else labels["no_features"]


def build_prompt(analysis: AIAnalysis, language: str = DEFAULT_LANGUAGE) -> str:
    labels = _PROMPT_LABELS[_normalize_language(language)]
    probabilities = analysis.probabilities or {}
    prob_lines = "\n".join(f"- {cls}: {p:.1%}" for cls, p in sorted(probabilities.items(), key=lambda kv: -kv[1]))
    return (
        f"{labels['predicted_class']}: {analysis.predicted_class}\n"
        f"{labels['probabilities']}:\n{prob_lines}\n\n"
        f"{labels['consistency']}:\n"
        f"{_format_biomarker_consistency(analysis.biomarker_consistency, labels)}\n\n"
        f"{labels['closing']}"
    )


def generate_explanation(analysis: AIAnalysis, language: str = DEFAULT_LANGUAGE) -> str:
    settings = get_settings()
    normalized = _normalize_language(language)
    prompt = build_prompt(analysis, normalized)
    try:
        response = httpx.post(
            f"{settings.ollama_url}/api/generate",
            json={
                "model": settings.ollama_model,
                "system": _SYSTEM_PROMPTS[normalized],
                "prompt": prompt,
                "stream": False,
            },
            timeout=_GENERATION_TIMEOUT_S,
        )
    except httpx.HTTPError as exc:
        raise LlmExplanationError(
            f"could not reach Ollama at {settings.ollama_url} "
            f"(is it running? see docs/llm-explanation.md): {exc}"
        ) from exc
    if response.status_code != 200:
        raise LlmExplanationError(f"Ollama returned {response.status_code}: {response.text}")
    body = response.json()
    text = (body.get("response") or "").strip()
    if not text:
        raise LlmExplanationError("Ollama returned an empty response")
    return text
