"""EPIC-18: LLM textual explanation cache on ai_analyses

Adds llm_explanation (nullable Text — cached natural-language suggestion
generated by a local Ollama/Qwen2.5 model from predicted_class/
probabilities/biomarker_consistency, see app.services.llm_explanation_service)
and llm_explanation_error (nullable — honest reason when generation itself
failed, e.g. Ollama not running; same non-blocking, never-fabricate pattern
as gradcam_error/biomarker_consistency_error). Cached rather than
regenerated on every view since it's a real model call, not a cheap lookup.

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-18
"""
import sqlalchemy as sa
from alembic import op

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("ai_analyses", sa.Column("llm_explanation", sa.Text(), nullable=True))
    op.add_column("ai_analyses", sa.Column("llm_explanation_error", sa.String(2000), nullable=True))


def downgrade() -> None:
    op.drop_column("ai_analyses", "llm_explanation_error")
    op.drop_column("ai_analyses", "llm_explanation")
